### ISSUE TITLE
Can't open PR - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Syakhisk** [JohnTheGr8/Flow.Plugin.Github#3]
Error window pops up with these messages, steps to reproduce:
- gh repos <repo-name>
- select PR menu item

```
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\OMG\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/05/2023 22:41:25
Exception:
GitHub Exception: 
Websites: https://github.com/JohnTheGr8/Flow.Plugin.Github
Author: Ioannis G. (@JohnTheGr8)
Version: 1.2.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$Flow-Plugin-Github>.$GithubPlugin.clo@71-14.GenerateNext(IEnumerable`1& next) in C:\projects\flow-plugin-github\src\GithubPlugin.fs:line 0
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$Flow-Plugin-Github>.$GithubPlugin.func2@1(GithubPlugin this, FSharpChoice`2 _arg4) in C:\projects\flow-plugin-github\src\unknown:line 134
   at <StartupCode$Flow-Plugin-Github>.$GithubPlugin.-ctor@131-2.Invoke(FSharpAsync`1 x) in C:\projects\flow-plugin-github\src\GithubPlugin.fs:line 131
   at Flow.Plugin.Github.GithubPlugin.Flow.Launcher.Plugin.IPlugin.Query(Query query) in C:\projects\flow-plugin-github\src\GithubPlugin.fs:line 148
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by JohnTheGr8** [comment]
Could you please share the exact queries that cause an exception for you? I tried to reproduce with no luck...
